---
- hosts: all
  become: true
  tasks:
  - name: install java
    apt:
      pkg: default-jdk
      state: present
  - name: install maven
    apt:
      pkg: maven
      state: present
    notify:
    - run update
  - name: install docker
    apt:
      pkg: docker.io
      state: present
  - name: install nginx
    apt:
      pkg: nginx
      state: present
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
  - name: Stop already existing containers
    command: sudo docker stop $(docker ps -aq)
  - name: Remove stopped containers
    command: sudo docker rm $(docker ps -aq)
  - name: deploy myTestApp application
    command: sudo docker run --name tomcat -it -d -p 8888:8888 anupabenny/images-repo1:tomcat-MyTestApp-image
  handlers:
  - name: run update
    apt:
      update_cache: yes
